name: Run core tests
description: Runs the tests on a limited set of OS and Git versions.
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - 'docs/**'
  push:
    branches: 
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - 'docs/**'

jobs:
  run-tests:
    name: "Run tests on ${{ matrix.runs-on }} with Git v${{ matrix.git-version }}"
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm, macos-14]
        git-version: ["2.44.0"]
        include:
          - runs-on: windows-2022
            git-version: 2.44.0.windows.1
    uses: ./.github/workflows/run-tests.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      git-version: ${{ matrix.git-version }}
